import { Column, Entity, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { Haiku } from '../../haiku/entities/haiku.entity';
import { ApiProperty } from '@nestjs/swagger';

@Entity()
export class Country {
  @ApiProperty({ description: 'ID of the country record.' })
  @PrimaryGeneratedColumn()
  id: number;

  @ApiProperty({ description: 'Name of the country.' })
  @Column('text')
  name: string;

  @ApiProperty({ description: 'Abbreviation for the country.' })
  @Column('text')
  abbr: string;

  @ApiProperty({ description: 'Haikus that were generated by this country.' })
  @OneToMany(() => Haiku, (haiku) => haiku.country)
  haikus: Haiku[];
}
